# SELECT AVG(DAILY_FEE) AS AVERAGE_FEE
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = 'SUV'

# SELECT  ROUND(AVG(DAILY_FEE),0) AS AVERAGE_FEE
# FROM  CAR_RENTAL_COMPANY_CAR 
# WHERE  CAR_TYPE = "SUV"
 
# SELECT ROUND(AVG(DAILY_FEE)) AS AVERAGE_FEE
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = 'SUV'

SELECT ROUND(AVG(a.DAILY_FEE)) AS AVERAGE_FEE 
FROM CAR_RENTAL_COMPANY_CAR a
WHERE 1=1
AND a.CAR_TYPE = 'SUV'
