# SELECT A.ANIMAL_ID, A.NAME 
# FROM ANIMAL_INS AS A, ANIMAL_OUTS AS B 
# WHERE A.ANIMAL_ID = B.ANIMAL_ID 
# ORDER BY B.DATETIME - A.DATETIME 
# DESC LIMIT 2

SELECT  O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O INNER JOIN  ANIMAL_INS AS I ON  O.ANIMAL_ID = I.ANIMAL_ID
ORDER   BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT   2;