# -- 코드를 입력하세요
# SELECT ANIMAL_TYPE, IF NULL(NAME, 'NO NAME'), SEX_UPON_INTAKE
# FROM ANIMAL_INS
# ORDER BY ANIMAL_ID;

SELECT ANIMAL_TYPE, IFNULL(NAME,'No name') AS NAME ,SEX_UPON_INTAKE 
from ANIMAL_INS
order by ANIMAL_ID;