SELECT ANIMAL_ID, NAME, 
CASE WHEN SEX_UPON_INTAKE LIKE '%Neutered%' 
# Neutered% , Spayed%
OR SEX_UPON_INTAKE LIKE '%Spayed%' THEN 'O' 
ELSE 'X' END AS 중성화 
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID;

SELECT ANIMAL_ID, NAME, 
IF(SEX_UPON_INTAKE LIKE '%NEUTERED%' OR SEX_UPON_INTAKE LIKE '%SPAYED%','O','X') 
AS 중성화 
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID;
