# 1
# SELECT ANIMAL_ID, NAME
# FROM ANIMAL_INS
# WHERE INTAKE_CONDITION LIKE 'Sick'
# ORDER BY ANIMAL_ID ASC;

# 2
# SELECT ANIMAL_ID, NAME 
# FROM ANIMAL_INS
# WHERE INTAKE_CONDITION = 'Sick'
# ORDER BY ANIMAL_ID

# 3
SELECT ANIMAL_ID, NAME 
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'