# SELECT A.NAME, A.DATETIME
# FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE B.DATETIME IS NULL
# ORDER BY A.DATETIME
# LIMIT 3;

# SELECT NAME, DATETIME
# FROM ANIMAL_INS
# WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
# ORDER BY DATETIME
# LIMIT 3;

SELECT NAME, DATETIME FROM ANIMAL_INS A
WHERE NOT EXISTS 
(SELECT ANIMAL_ID FROM ANIMAL_OUTS B WHERE A.ANIMAL_ID = B.ANIMAL_ID)
ORDER BY DATETIME
LIMIT 3;
