# SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
# FROM BOOK A LEFT JOIN BOOK_SALES BS ON A.BOOK_ID = BS.BOOK_ID
# WHERE SALES_DATE LIKE '%2022-01%'
# GROUP BY CATEGORY
# ORDER BY CATEGORY ASC;

# SELECT A.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
# FROM BOOK A JOIN BOOK_SALES BS ON A.BOOK_ID = BS.BOOK_ID
# WHERE BS.SALES_DATE LIKE '2022-01%'
# GROUP BY A.CATEGORY
# ORDER BY A.CATEGORY

# SELECT A.CATEGORY, SUM(SALES) AS TOTAL_SALES
# FROM BOOK A INNER JOIN BOOK_SALES BS ON A.BOOK_ID = BS.BOOK_ID
# WHERE BS.SALES_DATE LIKE '2022-01%'
# GROUP BY A.CATEGORY
# ORDER BY A.CATEGORY

# SELECT CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
# FROM BOOK A, BOOK_SALES BS
# WHERE A.BOOK_ID = BS.BOOK_ID AND SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
# GROUP BY CATEGORY
# ORDER BY CATEGORY ASC

# SELECT A.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
# FROM BOOK A JOIN BOOK_SALES BS ON A.BOOK_ID = BS.BOOK_ID
# WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
# GROUP BY A.CATEGORY
# ORDER BY A.CATEGORY

# SELECT A.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
# FROM BOOK AS A, BOOK_SALES AS BS
# WHERE YEAR(BS.SALES_DATE) = '2022' AND MONTH(BS.SALES_DATE) = '01' 
# AND BS.BOOK_ID = A.BOOK_ID
# GROUP BY A.CATEGORY
# ORDER BY A.CATEGORY

SELECT A.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK A LEFT JOIN BOOK_SALES BS on A.BOOK_ID = BS.BOOK_ID 
WHERE BS.SALES_DATE BETWEEN STR_TO_DATE('2022-01-01' ,'%Y-%m-%d') AND STR_TO_DATE('2022-01-31' ,'%Y-%m-%d')
GROUP BY A.category
ORDER BY A.category 
