SELECT A.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK A LEFT JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE LIKE '%2022-01%'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;

# SELECT b.CATEGORY, SUM(bs.SALES) AS TOTAL_SALES
# FROM BOOK b
# JOIN BOOK_SALES bs
# ON b.BOOK_ID = bs.BOOK_ID
# WHERE bs.SALES_DATE LIKE '2022-01%'
# GROUP BY b.CATEGORY
# ORDER BY b.CATEGORY